version: "3"

services:
    plex-utills:
        image: jkirkcaldy/plex-utills
        container_name: plex-utills
        restart: unless-stopped
        volumes: 
            - /mnt/plex:/films
            - /opt/plex-uitills:/config